// Verified Philippine Law questions for CSE General Information.
// Sourced from CSE reviewer sites & official statutes (RA 6713, RA 3019, 1987 Constitution).
// lahat ng sagot ay naka-check sa mga source.

// Para sa Subprofessional (Non-Pro) — mas pangunahing batas
export const lawNonPro = [
  { q: "Ano ang pamagat ng R.A. 6713?", options: ["Anti-Graft and Corrupt Practices Act", "Code of Conduct and Ethical Standards for Public Officials and Employees", "Local Government Code", "Administrative Code of 1987"], answer: 1, topic: "General Info", explanation: "Ang RA 6713 ay ang 'Code of Conduct and Ethical Standards for Public Officials and Employees' — itinatakda ang norms of conduct para sa mga opisyal at empleyado ng pamahalaan.", icon: "⚖️" },
  { q: "Kailan kailangang magresign sa pribadong negosyo ang isang opisyal kung may conflict of interest sa pag-upo sa pwesto?", options: ["15 araw", "30 araw", "60 araw", "90 araw"], answer: 1, topic: "General Info", explanation: "Ayon sa RA 6713, dapat magresign sa pribadong negosyo sa loob ng 30 araw mula sa pag-upo sa pwesto kung may conflict of interest.", icon: "🗓️" },
  { q: "Ilang araw ang ibinibigay para makumpleto ang divestment (pag-alis ng interes) pagkatapos pumwesto?", options: ["15 araw", "30 araw", "60 araw", "90 araw"], answer: 2, topic: "General Info", explanation: "Ang divestment ay dapat makumpleto sa loob ng 60 araw mula sa pag-upo sa pwesto ayon sa RA 6713.", icon: "📉" },
  { q: "Sino ang kabilang sa 'family' ng isang opisyal ayon sa RA 6713?", options: ["Asawa, mga anak na walang asawa na wala pang 18 taon", "Asawa, anak, magulang, at kapatid", "Lahat ng kamag-anak hanggang ika-apat na antas", "Asawa at lahat ng anak"], answer: 0, topic: "General Info", explanation: "Ang 'family' ay limitado sa asawa at mga anak na walang asawa at wala pang labingwalong taong gulang.", icon: "👨‍👩‍👧" },
  { q: "Ano ang kahulugan ng 'substantial stockholder' sa ilalim ng RA 6713?", options: ["May-ari ng anumang bahagi ng stock", "May-ari ng hindi bababa sa 1% ng stock", "May sapat na stock upang makapaghalal ng direktor", "May-ari ng mayorya ng stock"], answer: 2, topic: "General Info", explanation: "Ang substantial stockholder ay ang may hawak ng sapat na stock upang makapaghalal ng direktor ng korporasyon.", icon: "📊" },
  { q: "Aling regalo ang HINDI ipinagbabawal sa opisyal ng pamahalaan?", options: ["Mataas na halagang regalo mula sa kontratista", "Cash donation mula sa dayuhang gobyerno", "Travel expenses na inaprubahan ng pinuno ng opisina", "Business shares mula sa pribadong kompanya"], answer: 2, topic: "General Info", explanation: "Ang travel expenses na inaprubahan ng pinuno ng opisina ay itinuturing na exception sa pagbabawal ng regalo sa ilalim ng RA 6713.", icon: "✈️" },
  { q: "Kailan dapat mag-file ng Statement of Assets, Liabilities, and Net Worth (SALN) ang opisyal?", options: ["Kaagad", "Sa loob ng 15 araw", "Sa loob ng 30 araw", "Sa loob ng 60 araw"], answer: 2, topic: "General Info", explanation: "Ayon sa RA 6713, dapat mag-file ng SALN sa loob ng 30 araw mula sa pag-upo sa pwesto.", icon: "📄" },
  { q: "Ano ang HINDI kinakailangang ideklara sa SALN?", options: ["Real property", "Personal property", "Liabilities", "Political affiliation"], answer: 3, topic: "General Info", explanation: "Ang political affiliation ay HINDI kasama sa kailangang ideklara sa SALN — real property, personal property, liabilities, at financial interests lamang.", icon: "🗳️" },
  { q: "Anong aksyon ang lumalabag sa prinsipyong 'political neutrality'?", options: ["Paglilingkod sa lahat ng mamamayan nang pantay", "Pangangampanya para sa kandidato sa oras ng trabaho", "Pagbibigay ng pantay na serbisyo", "Pagsunod sa batas"], answer: 1, topic: "General Info", explanation: "Ang pangangampanya para sa isang kandidato habang nasa oras ng opisina ay paglabag sa political neutrality sa ilalim ng RA 6713.", icon: "🚫" },
  { q: "Ano ang pinakamagandang paglalarawan ng 'responsiveness to the public'?", options: ["Hindi pagpansin sa reklamo", "Pagpapabagal sa serbisyo", "Mabilis at magalang na serbisyo", "Paglilimita ng impormasyon"], answer: 2, topic: "General Info", explanation: "Ang responsiveness ay nangangailangan ng mabilis, sapat, at magalang na paglilingkod sa publiko.", icon: "🤝" },
  { q: "Paano dapat gamitin ang SALN?", options: ["Para sa anumang layunin", "Para sa komersyal na pakinabang", "Hindi ito dapat gamitin laban sa public policy", "Laging sikreto"], answer: 2, topic: "General Info", explanation: "Ang SALN ay hindi dapat gamitin nang salungat sa public policy o sa komersyal na layunin.", icon: "🔒" },
  { q: "Aling prinsipyo ang nagbibigay-diin sa katapatan sa bayan kaysa sa partido?", options: ["Propesyonalismo", "Nationalism and Patriotism", "Responsiveness", "Simple Living"], answer: 1, topic: "General Info", explanation: "Ang Nationalism and Patriotism ay nangangailangan ng katapatan sa Republika kaysa sa anumang partidong pampulitika.", icon: "🇵🇭" },
  { q: "Aling sitwasyon ang lumalabag sa patakaran tungkol sa mga kamag-anak?", options: ["Pagtanggap ng qualified na kamag-anak sa tamang proseso", "Pagbibigay ng hindi nararapat na pabor sa kamag-anak gamit ang kapangyarihan", "Pagdeklara ng kamag-anak sa SALN", "Pag-iwas sa conflict of interest"], answer: 1, topic: "General Info", explanation: "Ang pagbibigay ng hindi nararapat na pabor sa kamag-anak gamit ang opisyal na kapangyarihan ay paglabag sa RA 6713 (nepotismo).", icon: "⛔" },
  { q: "Ano ang diwa ng accountability sa ilalim ng RA 6713?", options: ["Mag-ulat lamang kapag tinanong", "Kumilos nang walang pangangasiwa", "Managot sa publiko sa lahat ng oras", "Ipagkatiwala ang responsibilidad"], answer: 2, topic: "General Info", explanation: "Ang mga opisyal ay dapat managot sa taumbayan sa lahat ng oras para sa kanilang mga aksyon at desisyon.", icon: "🎯" },
  { q: "Aling gawain ang lumalabag sa wastong paggamit ng resources ng gobyerno?", options: ["Mahusay na paggamit ng budget", "Paggamit ng kagamitan ng opisina para sa pribadong negosyo", "Public consultation", "Pagpa-file ng mga ulat"], answer: 1, topic: "General Info", explanation: "Ang mga kagamitan at resources ng pamahalaan ay para sa pampublikong layunin lamang, hindi para sa pribadong negosyo.", icon: "🖥️" },
  { q: "Kailan may 'conflict of interest' ang isang opisyal?", options: ["May-ari ng shares sa dayuhang kompanya na walang kaugnayan sa tungkulin", "Miyembro ng board ng pribadong kompanya na apektado ng opisyal na desisyon", "Tumanggap ng suweldo mula sa gobyerno", "Sumasali sa public consultations"], answer: 1, topic: "General Info", explanation: "May conflict of interest kung ang pribadong interes ng opisyal ay maaaring makaapekto sa kanyang opisyal na tungkulin.", icon: "⚠️" },
  { q: "Ang isang opisyal ay tumanggap ng mamahaling regalo mula sa kontratista sa Pasko. Ano ito sa ilalim ng RA 6713?", options: ["Normal na courtesy", "Paglabag sa batas — pagtanggap ng regalo", "Okay kung ire-report", "Bahagi ng trabaho"], answer: 1, topic: "General Info", explanation: "Ang pagtanggap ng mataas na halagang regalo mula sa isang kontratista ay ipinagbabawal dahil maaaring maka-impluwensya sa opisyal na desisyon.", icon: "🎁" },
  { q: "Ano ang ibig sabihin ng 'divestment'?", options: ["Pagdeklara ng assets sa publiko", "Paglipat ng pagmamay-ari sa kamag-anak", "Kumpletong pag-alis ng interes sa ibang tao", "Pagyeyelo ng negosyo assets"], answer: 2, topic: "General Info", explanation: "Ang divestment ay ang kumpletong pagtatanggal ng interes o pagmamay-ari sa isang negosyo, hindi basta paglipat sa kamag-anak.", icon: "💼" },
  { q: "Aling samahan ang HINDI kasapi ng Constitutional Commission?", options: ["Commission on Civil Rights", "Commission on Elections (COMELEC)", "Civil Service Commission (CSC)", "Commission on Audit (COA)"], answer: 0, topic: "General Info", explanation: "Ang tatlong constitutional commissions ay CSC, COMELEC, at COA. Ang 'Commission on Civil Rights' ay hindi umiiral sa ganyang pangalan.", icon: "🏛️" },
];

// Para sa Professional — mas mahirap na batas at konstitusyon
export const lawPro = [
  { q: "Ilan ang kasapi ng Senado ng Pilipinas?", options: ["21", "22", "23", "24"], answer: 3, topic: "General Info", explanation: "Ang Senado ay binubuo ng 24 senador na inihalal nang at-large ng mga botante.", icon: "🏛️" },
  { q: "Gaano katagal ang termino ng isang senador?", options: ["3 taon", "4 taon", "5 taon", "6 taon"], answer: 3, topic: "General Info", explanation: "Ang mga senador ay may terminong 6 na taon.", icon: "⏳" },
  { q: "Ilang miyembro ang bumubuo sa Korte Suprema?", options: ["Isang Chief Justice at 12 Associate Justices", "Isang Chief Justice at 13 Associate Justices", "Isang Chief Justice at 14 Associate Justices", "Isang Chief Justice at 15 Associate Justices"], answer: 2, topic: "General Info", explanation: "Ang Korte Suprema ay binubuo ng isang Chief Justice at 14 na Associate Justices, ayon sa 1987 Konstitusyon.", icon: "⚖️" },
  { q: "Kanino nakaatang ang kapangyarihang ehekutibo (executive power)?", options: ["Kongreso", "Kapulungan ng mga Kinatawan", "Pangulo ng Pilipinas", "Korte Suprema"], answer: 2, topic: "General Info", explanation: "Ang kapangyarihang ehekutibo ay nakasalalay sa Pangulo ng Pilipinas.", icon: "🇵🇭" },
  { q: "Gaano katagal ang termino ng Pangulo at Pangalawang Pangulo?", options: ["3 taon", "4 taon", "5 taon", "6 taon"], answer: 3, topic: "General Info", explanation: "Ang Pangulo at Pangalawang Pangulo ay may terminong 6 na taon, walang re-election ang Pangulo.", icon: "🕰️" },
  { q: "Gaano katagal ang termino ng mga kasapi ng Kapulungan ng mga Kinatawan?", options: ["3 taon", "4 taon", "5 taon", "6 taon"], answer: 0, topic: "General Info", explanation: "Ang mga kasapi ng Kapulungan ng mga Kinatawan ay may terminong 3 taon.", icon: "🗳️" },
  { q: "Ano ang kapangyarihan ng Estado na magsulong ng public welfare sa pamamagitan ng pagpigil sa paggamit ng kalayaan at ari-arian ng tao?", options: ["Power to Impeach", "Police Power", "Power of Eminent Domain", "Power of Taxation"], answer: 1, topic: "General Info", explanation: "Ang Police Power ay ang kapangyarihan ng Estado na magsulong ng kabutihang panlahat sa pamamagitan ng pagregula ng kalayaan at ari-arian.", icon: "🛡️" },
  { q: "Ano ang kapangyarihan ng Estado na magpataw ng buwis para sa kita ng pamahalaan?", options: ["Power of Taxation", "Power of Eminent Domain", "Police Power", "Power to Impeach"], answer: 0, topic: "General Info", explanation: "Ang Power of Taxation ay ang kapangyarihan ng Estado na magpataw ng buwis o singil sa tao at ari-arian upang makalikom ng kita para sa pamahalaan.", icon: "💰" },
  { q: "Ano ang kapangyarihan ng Estado na kumuha ng pribadong ari-arian para sa pampublikong gamit na may just compensation?", options: ["Power to Impeach", "Police Power", "Power of Taxation", "Power of Eminent Domain"], answer: 3, topic: "General Info", explanation: "Ang Power of Eminent Domain ay ang pagkuha ng pribadong ari-arian para sa pampublikong paggamit kapalit ng just compensation.", icon: "🏗️" },
  { q: "Alin ang HINDI kabilang sa tatlong inherent powers ng Estado?", options: ["Police Power", "Power of Eminent Domain", "Power of Taxation", "Power to Impeach"], answer: 3, topic: "General Info", explanation: "Ang tatlong inherent powers ay police power, power of eminent domain, at power of taxation. Ang power to impeach ay hindi kabilang.", icon: "❌" },
  { q: "Ano ang tawag sa karapatan at tungkulin ng mamamayan na 18 taong gulang pataas na bumoto?", options: ["Election", "Suffrage", "Civil Right", "Voting Power"], answer: 1, topic: "General Info", explanation: "Ang suffrage ay ang karapatan at tungkulin ng mamamayan na 18 taong gulang pataas na bumoto sa mga halalan.", icon: "🗳️" },
  { q: "Ilang boto ng Kongreso (dalawang kapulungan sa joint session) ang kailangan para magdeklara ng digmaan?", options: ["Dalawang-ikatlo (2/3)", "Kalahati (1/2)", "Tatlong-kapat (3/4)", "Minority"], answer: 0, topic: "General Info", explanation: "Ayon sa Konstitusyon, kailangan ang dalawang-ikatlong boto ng parehong kapulungan sa joint session para magdeklara ng digmaan.", icon: "⚔️" },
  { q: "Aling artikulo ng Konstitusyon ang tinatawag na Bill of Rights?", options: ["Artikulo II", "Artikulo III", "Artikulo IV", "Artikulo V"], answer: 1, topic: "General Info", explanation: "Ang Bill of Rights ay nakapaloob sa Artikulo III ng 1987 Konstitusyon, na nagpoprotekta sa mga karapatan ng indibidwal.", icon: "📜" },
  { q: "Aling sangay ng pamahalaan ang may kapangyarihang mag-akusahan o mag-audit ng mga pondo?", options: ["Department of Budget", "Commission on Audit", "Department of Public Works", "Bureau of Internal Revenue"], answer: 1, topic: "General Info", explanation: "Ang Commission on Audit (COA) ang may kapangyarihang mag-examine, mag-audit, at mag-settle ng mga account ng pamahalaan.", icon: "🔍" },
  { q: "Gaano katagal may oras ang Pangulo para i-veto ang isang bill bago ito maging batas?", options: ["15 araw", "21 araw", "30 araw", "45 araw"], answer: 2, topic: "General Info", explanation: "Ayon sa Artikulo VI, Seksyon 27 ng Konstitusyon, may 30 araw ang Pangulo para i-veto ang isang bill; kung hindi, ito ay magiging batas.", icon: "🖋️" },
  { q: "Ilang boto ang kailangan para ma-expel ang isang miyembro ng Kongreso?", options: ["Majority", "Isang-kapat (1/4)", "Dalawang-ikatlo (2/3)", "Tatlong-kapat (3/4)"], answer: 2, topic: "General Info", explanation: "Ayon sa Artikulo VI, Seksyon 16(3), kailangan ang concurrence ng dalawang-ikatlo ng lahat ng miyembro para ma-suspend o ma-expel ang isang miyembro.", icon: "⚖️" },
  { q: "Aling pahayag ang totoo tungkol sa ex post facto law?", options: ["Maaaring parusahan ang nakaraang gawain na hindi pa ilegal", "Ipinagbabawal ng Konstitusyon ang ex post facto law", "Kailangan para sa pambansang seguridad", "Laging legal"], answer: 1, topic: "General Info", explanation: "Ipinagbabawal ng Saligang Batas ang ex post facto law at bill of attainder — hindi maaaring parusahan ang gawain na hindi ilegal noong ginawa.", icon: "📖" },
  { q: "Sa ilalim ng R.A. 3019 (Anti-Graft and Corrupt Practices Act), sino ang maaaring managot sa graft?", options: ["Publiko at pribadong indibidwal na nag-uudyok ng korapsyon", "Mga pampublikong opisyal lamang", "Mga pribadong negosyante lamang", "Walang sinuman"], answer: 0, topic: "General Info", explanation: "Ang RA 3019 ay sumasaklaw sa parehong pampublikong opisyal at pribadong indibidwal na nag-uudyok ng korapsyon.", icon: "🚔" },
  { q: "Ano ang prescriptive period (panahon ng pag-uusig) para sa mga kaso sa ilalim ng RA 3019?", options: ["5 taon", "10 taon", "15 taon", "20 taon"], answer: 3, topic: "General Info", explanation: "Ang prescriptive period para sa RA 3019 ay 20 taon, pinalawig ng RA 10910 noong 2016.", icon: "⏰" },
  { q: "Aling korte ang humahawak ng mga kaso ng mga opisyal na may Salary Grade 27 pataas sa ilalim ng RA 3019?", options: ["Korte Suprema", "Sandiganbayan", "Regional Trial Court", "Municipal Trial Court"], answer: 1, topic: "General Info", explanation: "Ang Sandiganbayan, ang espesyal na anti-graft court, ang humahawak ng mga kaso ng mga opisyal na may SG 27 pataas.", icon: "🏛️" },
  { q: "Ano ang parusa para sa paglabag sa RA 3019?", options: ["6 na buwan hanggang 2 taon", "2 hanggang 6 na taon", "6 na taon at 1 buwan hanggang 15 taon", "20 taon hanggang buhay"], answer: 2, topic: "General Info", explanation: "Ang parusa sa RA 3019 ay 6 na taon at 1 buwan hanggang 15 taon ng pagkabilanggo, kasama ang perpetual disqualification.", icon: "⛓️" },
  { q: "Ano ang tatlong mode ng paglabag sa Seksyon 3(e) ng RA 3019 (undue injury)?", options: ["Manifest partiality, evident bad faith, gross inexcusable negligence", "Panunuhol, pagnanakaw, pandaraya", "Pagnanakaw, pang-aabuso, pananakit", "Katiwalian, pagnanakaw, pandaraya"], answer: 0, topic: "General Info", explanation: "Ang Seksyon 3(e) ay nangangailangan ng isa sa tatlo: manifest partiality, evident bad faith, o gross inexcusable negligence.", icon: "📋" },
  { q: "Ang RA 3019 ay nilagdaan noong ___?", options: ["Agosto 17, 1960", "Pebrero 20, 1989", "Hunyo 12, 1987", "Enero 1, 2000"], answer: 0, topic: "General Info", explanation: "Ang RA 3019 (Anti-Graft and Corrupt Practices Act) ay nilagdaan noong Agosto 17, 1960.", icon: "📜" },
  { q: "Aling pahayag ang totoo tungkol sa RA 6713 at RA 3019?", options: ["Parehong itinatakda ang norms of conduct", "Ang RA 3019 ay nagpapataw ng parusa sa graft, ang RA 6713 ay nagtatakda ng ethical standards", "Ang RA 6713 ay anti-graft law", "Parehong walang kaugnayan sa mga opisyal"], answer: 1, topic: "General Info", explanation: "Ang RA 3019 ay nagpaparusa sa mga corrupt practices habang ang RA 6713 ay nagtatakda ng ethical standards at norms of conduct.", icon: "📊" },
  { q: "Aling pahayag ang HINDI kabilang sa mga tungkulin ng pampublikong opisyal ayon sa RA 6713?", options: ["Magproseso ng mga dokumento nang mabilis", "Magsumite ng performance reports", "Tumanggap ng regalo mula sa publiko para mapabilis ang serbisyo", "Kumilos agad sa mga sulat at tawag ng publiko"], answer: 2, topic: "General Info", explanation: "Ang pagtanggap ng regalo mula sa publiko ay HINDI tungkulin ng opisyal — ito ay ipinagbabawal.", icon: "🚫" },
  { q: "Ano ang mandatory na ibigay sa publiko ng bawat ahensiya ng gobyerno para sa kanilang mga transaksyon?", options: ["Ang mga rate ng service fees", "Ang performance targets", "Ang mga pangalan ng action officers", "Ang service guides"], answer: 3, topic: "General Info", explanation: "Ayon sa RA 9485 (Anti-Red Tape Act), mandatory para sa bawat ahensiya ang magbigay ng service guides sa publiko.", icon: "📘" },
];
