// Question Bank — Mastery Review PH
// Bawat test ay may `bank` (pool ng maraming tanong) at `sampleCount`.
// Sa bawat subok, RANDOM na pipili ang server ng `sampleCount` tanong mula sa bank.

import { extraTest1, extraTest2, extraTest3, extraTest4 } from './questions-extra.js';
import { lawNonPro, lawPro } from './questions-laws.js';

export const tests = [
  {
    id: 1,
    title: 'Practice Test #1 — Civil Service Professional',
    blurb: 'Verbal, Clerical, Analytical & Numerical — random questions bawat subok.',
    premium: false,
    examType: 'professional',
    sampleCount: 10,
    bank: [
      { q: 'Piliin ang salitang pinakamalapit sa kahulugan ng "Lucrative".', options: ['Praktikal', 'Marangal', 'Kapaki-pakinabang', 'Malungkot'], answer: 2, topic: "Verbal", explanation: '"Lucrative" ay nangangahulugang kumikita o kumikitang negosyo.', icon: '💡' },
      { q: 'Anong panahunan ang ginamit sa: "The committee has reached a decision."?', options: ['Simple present', 'Past perfect', 'Present perfect', 'Simple future'], answer: 2, topic: "Verbal", explanation: 'Ang "has reached" ay Present Perfect (aksyon na nagsimula sa nakaraan na may kaugnayan sa ngayon).', icon: '📚' },
      { q: 'Piliin ang tamang salita: "Either the manager or the assistants ___ responsible for the report."', options: ['is', 'are', 'was', 'were'], answer: 1, topic: "Verbal", explanation: 'Sa "either...or", sundin ang pinakamalapit na subject sa verb: "assistants" (plural), kaya "are".', icon: '✍️' },
      { q: 'Clerical: Piliin ang kopyang magkakapareho: `85F7 2L09 3MD4`', options: ['85F7 2L09 3MD4', '85F7 2L09 4MD3', '85F7 2L09 3MD5', '85T7 2L09 3MD4'], answer: 0, topic: "Clerical", explanation: 'Ang tamang kopya ay eksaktong pareho sa lahat ng numero at letra ng orihinal.', icon: '🔍' },
      { q: 'Piliin ang antonym (kasalungat) ng "PLACID".', options: ['Calm', 'Turbulent', 'Gentle', 'Quiet'], answer: 1, topic: "Verbal", explanation: 'Placid = matahimik/kalma. Ang kasalungat ay magulo — "turbulent."', icon: '🌊' },
      { q: 'Alin ang tamang spelling?', options: ['Neccessary', 'Necessary', 'Necessery', 'Necassary'], answer: 1, topic: "Verbal", explanation: '"Necessary" — one "c" at double "s" ang tamang spelling.', icon: '🔤' },
      { q: 'Sa salitang "REMEMBER", ilang beses lumitaw ang letrang E?', options: ['1', '2', '3', '4'], answer: 2, topic: "Clerical", explanation: 'R-E-M-E-M-B-E-R: tatlong E ang matatagpuan sa salita.', icon: '🔡' },
      { q: 'Piliin ang best synonym ng "Benevolent".', options: ['Malicious', 'Mabait (Kind)', 'Masungit (Strict)', 'Duwag (Fearful)'], answer: 1, topic: "Verbal", explanation: 'Benevolent = mabait at may mabuting kalooban; ang pinakamalapit ay "kind."', icon: '❤️' },
      { q: 'Analogy: Kung ACTOR : STAGE, ang CHEF : _____', options: ['Kitchen', 'Food', 'Restaurant', 'Meal'], answer: 0, topic: "Analytical", explanation: 'Ang actor ay gumagawa sa stage; ang chef ay gumagawa sa kitchen. Ito ang pairing ng tao-lugar.', icon: '🧑‍🚒' },
      { q: 'Alin ang hindi kabilang sa grupo?', options: ['Galit (Angry)', 'Masaya (Happy)', 'Malungkot (Depressed)', 'Buwisit (Frustrated)'], answer: 1, topic: "Verbal", explanation: 'Ang tatlo (angry, depressed, frustrated) ay negatibong emosyon; masaya ang positibong.', icon: '😊' },
      { q: 'Kung ang 7 mansanas ay may halagang ₱140, magkano ang 3 mansanas?', options: ['₱40', '₱45', '₱60', '₱70'], answer: 2, topic: "Numerical", explanation: '140 ÷ 7 = 20 per mansanas; 3 × 20 = ₱60.', icon: '🍎' },
      { q: 'I-solve: 25% ng 180', options: ['35', '45', '55', '65'], answer: 1, topic: "Numerical", explanation: '25% = 1/4. 180 ÷ 4 = 45.', icon: '➗' },
      { q: 'Ano ang susunod na numero: 2, 6, 12, 20, 30, ____?', options: ['36', '40', '42', '44'], answer: 2, topic: "Numerical", explanation: 'Pagkakaiba: +4, +6, +8, +10 → susunod ay +12. 30+12 = 42.', icon: '🔢' },
      { q: 'Isang kotse ang naglakbay ng 90 km sa 1.5 oras. Ano ang bilis (km/h)?', options: ['50', '60', '70', '80'], answer: 1, topic: "Numerical", explanation: 'Speed = distansya ÷ oras = 90 ÷ 1.5 = 60 km/h.', icon: '🚗' },
      { q: 'I-simplify: 48 ÷ 6 × 2 − 4', options: ['4', '8', '12', '16'], answer: 2, topic: "Verbal", explanation: 'Sundin ang order ng operasyon: 48÷6=8, 8×2=16, 16−4=12.', icon: '🧮' },
      { q: 'Magkano ang 3/4 ng ₱1,200?', options: ['₱700', '₱850', '₱900', '₱950'], answer: 2, topic: "Numerical", explanation: '1200 × 3/4 = 3600 ÷ 4 = ₱900.', icon: '💵' },
      { q: 'Ang ratio ng lalaki : babae ay 3 : 5. Kung may 30 babae, ilan ang lalaki?', options: ['16', '18', '20', '24'], answer: 1, topic: "Numerical", explanation: '30 ÷ 5 = 6 (bawat bahagi). Lalaki = 3 × 6 = 18.', icon: '⚖️' },
      { q: 'I-round off ang 7,845 sa pinakamalapit na libo:', options: ['7,000', '7,800', '8,000', '8,800'], answer: 2, topic: "Numerical", explanation: 'Ang libo ay 7; ang daanan (8) ay ≥ 5, kaya i-round up → 8,000.', icon: '🔟' },
      { q: 'Ang isang damit ay ₱800 na may 20% discount. Magkano ang bayaran?', options: ['₱600', '₱640', '₱680', '₱700'], answer: 1, topic: "Numerical", explanation: '800 × 0.20 = 160; 800 − 160 = ₱640.', icon: '🛍️' },
      { q: 'Average ng: 10, 20, 30, 40, 50', options: ['25', '30', '35', '40'], answer: 1, topic: "Numerical", explanation: 'Sum = 150 ÷ 5 numero = 30.', icon: '📊' },
      { q: 'Piliin ang tamang salita: "He ___ to school every day."', options: ['go', 'goes', 'going', 'gone'], answer: 1, topic: "Verbal", explanation: 'Sa third person singular ("he"), ang verb ay may -es: "goes."', icon: '🎓' },
      { q: 'Piliin ang antonym ng "Temporary".', options: ['Permanent', 'Momentary', 'Brief', 'Short'], answer: 0, topic: "Verbal", explanation: 'Ang temporary ay pansamantala; ang kasalungat nito ay permanent.', icon: '⏳' },
      { q: 'Ano ang kahulugan ng idiom na "break a leg"?', options: ['Magpapakalbo', 'Good luck', 'Masira ang binti', 'Mag-away'], answer: 1, topic: "Verbal", explanation: 'Ang "break a leg" ay idioma para sa "good luck" lalo na sa entablado.', icon: '🍀' },
      { q: 'Clerical: Piliin ang kopyang magkakapareho: `A1B2 C3D4 E5F6`', options: ['A1B2 C3D4 E5F6', 'A1B2 C4D4 E5F6', 'A1B2 C3D4 E5F7', 'A1B3 C3D4 E5F6'], answer: 0, topic: "Clerical", explanation: 'Ang tamang kopya ay walang pinagbago sa mga numero at letra.', icon: '🔍' },
      { q: 'Kung 5 mangga ay ₱125, magkano ang 2 mangga?', options: ['₱40', '₱50', '₱60', '₱25'], answer: 1, topic: "Numerical", explanation: '125 ÷ 5 = 25 bawat mangga; 2 × 25 = ₱50.', icon: '🥭' },
      { q: 'I-solve: 10% ng 450', options: ['40', '45', '50', '55'], answer: 1, topic: "Numerical", explanation: '10% = 1/10. 450 ÷ 10 = 45.', icon: '➗' },
      { q: 'Ano ang susunod: 5, 10, 20, 40, ____?', options: ['60', '80', '90', '100'], answer: 1, topic: "Numerical", explanation: 'Bawat numero ay dumoble: ×2. 40 × 2 = 80.', icon: '🔢' },
      { q: 'Ano ang average ng: 4, 8, 12, 16?', options: ['8', '10', '12', '14'], answer: 1, topic: "Verbal", explanation: 'Sum = 40 ÷ 4 numero = 10.', icon: '📊' },
      { q: 'Kung ang 50% ng isang numero ay 200, ano ang numero?', options: ['300', '400', '500', '100'], answer: 1, topic: "Numerical", explanation: '200 ÷ 0.5 = 400.', icon: '💯' },
      { q: 'I-round ang 3,451 sa pinakamalapit na daan:', options: ['3,400', '3,450', '3,500', '3,000'], answer: 2, topic: "Numerical", explanation: 'Ang daanan na 5 ay ≥ 5, kaya i-round up: 3,500.', icon: '🔟' },
      { q: 'Piliin ang pinakamalapit na kahulugan ng "Courageous".', options: ['Matapang', 'Duweg', 'Matiisin', 'Madaldal'], answer: 0, topic: "Verbal", explanation: 'Courageous = matapang o may tapang.', icon: '🦁' },
      { q: 'Piliin ang tamang gramatika: "Neither of the answers ___ correct."', options: ['are', 'is', 'were', 'be'], answer: 1, topic: "Verbal", explanation: '"Neither" ay singular, kaya ang verb ay "is."', icon: '✍️' },
      { q: 'Ano ang antonym ng "Expand"?', options: ['Grow', 'Shrink', 'Increase', 'Stretch'], answer: 1, topic: "Verbal", explanation: 'Ang expand ay lumaki; ang antonym ay lumiit — "shrink."', icon: '↔️' },
      { q: 'Decimal: 0.5 bilang fraction', options: ['1/2', '1/3', '1/4', '2/5'], answer: 0, topic: "Verbal", explanation: '0.5 = 5/10 = 1/2.', icon: '🔢' },
      { q: 'Kung ang isang aklat ay ₱250 at 10% discount, magkano?', options: ['₱200', '₱225', '₱240', '₱215'], answer: 1, topic: "Numerical", explanation: '250 × 0.10 = 25; 250 − 25 = ₱225.', icon: '📖' },
      { q: 'Piliin ang tamang ispiling: "___"', options: ['Receive', 'Recieve', 'Receeve', 'Resieve'], answer: 0, topic: "Verbal", explanation: '"Receive" — "i before e" ay may pagbubukod pagkatapos ng "c."', icon: '🔤' },
      { q: 'Analogy: KUNG PEN : WRITE, ang SCISSORS : _____', options: ['Cut', 'Sew', 'Draw', 'Color'], answer: 0, topic: "Analytical", explanation: 'Ang pen ay ginagamit para magsulat; ang scissors ay para magcut.', icon: '✂️' },
      { q: 'Ang isang worker ay ₱120/oras at nagtrabaho 8 oras. Magkano ang kita?', options: ['₱860', '₱960', '₱960.50', '₱1,000'], answer: 1, topic: "Numerical", explanation: '120 × 8 = ₱960.', icon: '👷' },
      ...extraTest1,
    ],
  },
  {
    id: 2,
    title: 'Practice Test #2 — Civil Service Professional',
    blurb: 'Verbal, Clerical, Analytical & Numerical — premium, random questions.',
    premium: true,
    examType: 'professional',
    sampleCount: 10,
    bank: [
      { q: 'Piliin ang pinakamalapit na kahulugan ng "Frugal".', options: ['Masinop', 'Mapagbigay', 'Maramot', 'Palabiro'], answer: 0, topic: "Verbal", explanation: '"Frugal" = masinop o maingat sa paggastos.', icon: '💰' },
      { q: 'Piliin ang tamang gramatika: "Each of the students ___ to submit their form."', options: ['need', 'needs', 'needing', 'were'], answer: 1, topic: "Verbal", explanation: '"Each" ay singular, kaya ang verb ay "needs."', icon: '✍️' },
      { q: 'Analogy: Kung DOCTOR : HOSPITAL, ang Lawyer : _____', options: ['Courthouse', 'Office', 'School', 'Library'], answer: 0, topic: "Analytical", explanation: 'Ang doktor ay gumagawa sa ospital; ang lawyer sa korte (courthouse).', icon: '⚖️' },
      { q: 'Piliin ang salitang hindi kabilang:', options: ['Apple', 'Banana', 'Carrot', 'Mango'], answer: 2, topic: "Verbal", explanation: 'Ang apple, banana, mango ay prutas; ang carrot ay gulay.', icon: '🥕' },
      { q: 'Ispeling: Alin ang tamang salita? — "Environment"', options: ['Environment', 'Enviroment', 'Enviornment', 'Environmant'], answer: 0, topic: "Verbal", explanation: '"Environment" ang tamang spelling.', icon: '🌍' },
      { q: 'Piliin ang synonym ng "Abundant".', options: ['Kulang', 'Sagana', 'Masarap', 'Matamlay'], answer: 1, topic: "Verbal", explanation: '"Abundant" = disana, labis o marami.', icon: '🌾' },
      { q: 'Anong panahunan: "She has been living here since 2019."', options: ['Simple past', 'Present perfect continuous', 'Past perfect', 'Future perfect'], answer: 1, topic: "Numerical", explanation: '"has been living" ay Present Perfect Continuous (aksyon na patuloy hanggang ngayon).', icon: '📚' },
      { q: 'Piliin ang mali sa pangungusap: "The teacher gave me this book the other day yesterday."', options: ['gave', 'this', 'the other day', 'yesterday'], answer: 3, topic: "Verbal", explanation: 'Ang "the other day" at "yesterday" ay REDUNDANT — isa lang ang dapat.', icon: '⚠️' },
      { q: 'Clerical: Piliin ang kopyang magkakapareho: `A4B9 7C2K MH3L`', options: ['A4B9 7C2K MH3L', 'A4B9 7C2K MH2L', 'A4B8 7C2K MH3L', 'A4B9 7C3K MH3L'], answer: 0, topic: "Clerical", explanation: 'Ang orihinal ay eksaktong kopya ng numero at letra.', icon: '🔍' },
      { q: 'Piliin ang antonym ng "Expand".', options: ['Grow', 'Shrink', 'Increase', 'Stretch'], answer: 1, topic: "Verbal", explanation: 'Ang expand ay lumaki; ang antonym ay lumiit — "shrink."', icon: '↔️' },
      { q: 'Kung 3 item = ₱45, magkano ang 9 item?', options: ['₱90', '₱105', '₱135', '₱120'], answer: 2, topic: "Numerical", explanation: '45 ÷ 3 = 15 bawat item. 9 × 15 = ₱135.', icon: '🛒' },
      { q: 'I-solve: 15% ng 240', options: ['30', '36', '40', '45'], answer: 1, topic: "Numerical", explanation: '240 × 0.15 = 36.', icon: '➗' },
      { q: 'Ano ang susunod: 3, 5, 9, 17, 33, ____?', options: ['65', '66', '67', '68'], answer: 0, topic: "Numerical", explanation: 'Pattern: +2, +4, +8, +16 (×2 bawat paraan). Susunod: +32 → 65.', icon: '🔢' },
      { q: 'Isang tao ang naglakad ng 5 km sa 1 oras. Magkano ang layo sa 3.5 oras?', options: ['15.5 km', '17.5 km', '18.5 km', '20 km'], answer: 1, topic: "Numerical", explanation: '5 km/h × 3.5 = 17.5 km.', icon: '🏃' },
      { q: 'I-simplify: 9 + 3 × 7 − 15', options: ['11', '15', '20', '27'], answer: 1, topic: "Verbal", explanation: 'Order: 3×7=21; 9+21=30; 30−15=15.', icon: '🧮' },
      { q: 'Kung ang 25% ng isang numero ay 50, ano ang numero?', options: ['100', '120', '200', '250'], answer: 2, topic: "Numerical", explanation: '50 ÷ 0.25 = 200.', icon: '💯' },
      { q: 'Ang presyo ay ₱1,500. Dagdagan ng 30%, magkano?', options: ['₱1,800', '₱1,900', '₱1,950', '₱2,000'], answer: 2, topic: "Numerical", explanation: '1500 × 0.3 = 450; 1500 + 450 = ₱1,950.', icon: '📈' },
      { q: 'I-round ang 6,462 sa pinakamalapit na libo:', options: ['6,000', '6,400', '6,500', '7,000'], answer: 0, topic: "Numerical", explanation: 'Ang libo ay 6; ang daanan (4) ay < 5, kaya 6,000.', icon: '🔟' },
      { q: 'Decimal: 0.75 bilang fraction', options: ['3/5', '3/4', '2/3', '7/10'], answer: 1, topic: "Numerical", explanation: '0.75 = 75/100 = 3/4.', icon: '🔢' },
      { q: 'Kung ang average ng 6 na numero ay 15, ano ang sum?', options: ['80', '90', '100', '110'], answer: 1, topic: "Numerical", explanation: 'Average × bilang = sum: 15 × 6 = 90.', icon: '📊' },
      { q: 'Piliin ang tamang salita: "The news ___ very surprising."', options: ['is', 'are', 'were', 'be'], answer: 0, topic: "Verbal", explanation: '"News" ay isahan sa English, kaya "is."', icon: '📰' },
      { q: 'Ano ang antonym ng "Ancient"?', options: ['Modern', 'Old', 'Aged', 'Historic'], answer: 0, topic: "Verbal", explanation: 'Ancient = luma/sinauna; ang kasalungat ay modern o bago.', icon: '🏛️' },
      { q: 'Piliin ang synonym ng "Deliberate".', options: ['Accidental', 'Intentional', 'Random', 'Careless'], answer: 1, topic: "Verbal", explanation: 'Deliberate = sadya o sinasadya.', icon: '🎯' },
      { q: 'Clerical: `X9Y8 Z7W6 V5U4`', options: ['X9Y8 Z7W6 V5U4', 'X9Y8 Z7W5 V5U4', 'X9Y7 Z7W6 V5U4', 'X9Y8 Z7W6 V5U5'], answer: 0, topic: "Clerical", explanation: 'Eksaktong kopya ng numero at letra.', icon: '🔍' },
      { q: 'Kung 4 aklat ay ₱600, magkano ang 7 aklat?', options: ['₱900', '₱1,050', '₱1,100', '₱1,200'], answer: 1, topic: "Numerical", explanation: '600 ÷ 4 = 150 bawat aklat; 7 × 150 = ₱1,050.', icon: '📚' },
      { q: 'I-solve: 20% ng 350', options: ['60', '70', '80', '90'], answer: 1, topic: "Numerical", explanation: '350 × 0.20 = 70.', icon: '➗' },
      { q: 'Ano ang susunod: 1, 4, 9, 16, 25, ____?', options: ['30', '36', '40', '49'], answer: 1, topic: "Numerical", explanation: 'Ito ay perfect squares: 1², 2², 3², 4², 5² → 6² = 36.', icon: '🔢' },
      { q: 'Kung ang 12% ng isang numero ay 36, ano ang numero?', options: ['250', '300', '350', '400'], answer: 1, topic: "Numerical", explanation: '36 ÷ 0.12 = 300.', icon: '💯' },
      { q: 'Ano ang average ng: 12, 14, 16, 18?', options: ['14', '15', '16', '17'], answer: 1, topic: "Verbal", explanation: 'Sum = 60 ÷ 4 = 15.', icon: '📊' },
      { q: 'I-round ang 9,876 sa pinakamalapit na libo:', options: ['9,000', '9,800', '10,000', '9,900'], answer: 2, topic: "Numerical", explanation: 'Ang daanan (8) ay ≥ 5, kaya i-round up: 10,000.', icon: '🔟' },
      { q: 'Piliin ang antonym ng "Victory".', options: ['Defeat', 'Win', 'Triumph', 'Success'], answer: 0, topic: "Verbal", explanation: 'Ang victory ay tagumpay; ang kasalungat ay defeat.', icon: '🏆' },
      { q: 'Ispeling: Alin ang tamang salita? — "Accommodation"', options: ['Accommodation', 'Acomodation', 'Accomodation', 'Acommodation'], answer: 0, topic: "Verbal", explanation: '"Accommodation" — double c at double m.', icon: '🔤' },
      { q: 'Kung ang isang ticket ay ₱80 at bumili ng 5, magkano?', options: ['₱300', '₱350', '₱400', '₱450'], answer: 2, topic: "Numerical", explanation: '80 × 5 = ₱400.', icon: '🎟️' },
      { q: 'Ano ang halaga ng: 2² + 3²?', options: ['10', '12', '13', '25'], answer: 2, topic: "Verbal", explanation: '4 + 9 = 13.', icon: '🧮' },
      { q: 'Piliin ang tamang salita: "If I ___ rich, I would travel."', options: ['am', 'was', 'were', 'be'], answer: 2, topic: "Verbal", explanation: 'Sa second conditional, ginagamit ang "were" para sa lahat ng subjects.', icon: '🎓' },
      { q: 'Analogy: KUNG PEN : INK, ang CAR : _____', options: ['Road', 'Gasoline', 'Wheel', 'Driver'], answer: 1, topic: "Analytical", explanation: 'Ang pen ay nangangailangan ng ink; ang car ay nangangailangan ng gasolina.', icon: '⛽' },
      ...extraTest2,
    ],
  },
{
    id: 3,
    title: 'Practice Test #3 — Civil Service Subprofessional (Non-Professional)',
    blurb: 'General Information, Verbal, Clerical & Numerical — ayon sa tamang saklaw ng Subprofessional exam.',
    premium: true,
    examType: 'nonpro',
    sampleCount: 10,
    bank: [
      // ===== General Information =====
      { q: 'Ano ang kasalukuyang Saligang Batas ng Pilipinas?', options: ['1935 Constitution', '1973 Constitution', '1987 Constitution', '1985 Constitution'], answer: 2, topic: "General Info", explanation: 'Ang 1987 Saligang Batas ang kasalukuyang ginagamit, pinagtibay noong 1987 sa panahon ni Pangulong Corazon Aquino.', icon: '📜' },
      { q: 'Ilan ang pangunahing sangay ng pamahalaan ng Pilipinas?', options: ['Dalawang (2)', 'Tatlong (3)', 'Apat na (4)', 'Limang (5)'], answer: 1, topic: "General Info", explanation: 'May tatlong sangay: Ehekutibo (Pangulo), Lehislatibo (Kongreso), at Hudisyal (Korte Suprema).', icon: '🏛️' },
      { q: 'Alin sa mga sumusunod ang HINDI kayang gawin ng pamahalaan ayon sa Bill of Rights (Artikulo III)?', options: ['Maningil ng buwis', 'Arestuhin ang tao nang walang warrant', 'Maglabas ng batas', 'Magtayo ng paaralan'], answer: 1, topic: "General Info", explanation: 'Ang Bill of Rights ay nagpoprotekta sa mga mamamayan — bawal ang arestuhin nang walang warrants ng hukom.', icon: '⚖️' },
      { q: 'Ano ang tawag sa batas na nagtatakda ng kodigo ng asal sa mga pampublikong opisyal?', options: ['RA 6713', 'RA 9003', 'RA 8749', 'RA 2000'], answer: 0, topic: "General Info", explanation: 'Ang R.A. 6713 o "Code of Conduct and Ethical Standards for Public Officials and Employees" ang nagtatakda nito.', icon: '📋' },
      { q: 'Ayon sa Universal Declaration of Human Rights, ang mga karapatan ng tao ay ___.', options: ['Ibinibigay ng Estado', 'Likas at hindi maaalis', 'Pansamantala', 'Para lamang sa mamamayan ng bansa'], answer: 1, topic: "General Info", explanation: 'Ang mga karapatang pantao ay likas, unibersal, at hindi maaalis (inalienable) — hindi ibinibigay ng Estado kundi bahagi ng pagkatao.', icon: '🤝' },
      { q: 'Ano ang pangunahing layunin ng environment management and protection?', options: ['Pabilisin ang industriyalisasyon', 'Protektahan ang likas na yaman para sa susunod na henerasyon', 'Magtayo ng mas maraming pabrika', 'Dagdagan ang basura'], answer: 1, topic: "General Info", explanation: 'Ang layunin ay protektahan ang likas na yaman at tiyakin ang sustenableng pag-unlad para sa mga susunod na henerasyon.', icon: '🌱' },
      { q: 'Sa ilalim ng R.A. 6713, ano ang dapat gawin ng pampublikong opisyal sa mga regalo?', options: ['Tanggapin ang lahat', 'Huwag tumanggap maliban kung maliit lamang ang halaga', 'Itago sa lihim', 'Ibigay sa kamag-anak'], answer: 1, topic: "General Info", explanation: 'Sa ilalim ng RA 6713, bawal tumanggap ang opisyal ng regalo na may halagang higit sa nominal at maaaring makaapekto sa kanyang opisyal na tungkulin.', icon: '🎁' },
      // ===== Verbal Ability =====
      { q: 'Piliin ang salitang KASINGKAHULUGAN ng "masagana".', options: ['Salat', 'Sagana', 'Kapos', 'Dukha'], answer: 1, topic: "Verbal", explanation: 'Ang "masagana" ay nangangahulugang sagana o marami.', icon: '🇵🇭' },
      { q: 'Piliin ang KASALUNGAT (antonym) ng "maliwanag".', options: ['Matindi', 'Madilim', 'Maliit', 'Tahimik'], answer: 1, topic: "Verbal", explanation: 'Ang maliwanag ay may ningning; ang kasalungat nito ay madilim.', icon: '🌙' },
      { q: 'Wastong gamit ng wika: Piliin ang tamang pangungusap.', options: ['Ang bata ay naglalaro sa labas habang umuulan.', 'Ang bata ay naglalaro sa labas kaya umuulan.', 'Ang bata ay naglalaro habang umuulan sa labas.', 'Umuulan ang bata habang naglalaro sa labas.'], answer: 0, topic: "Verbal", explanation: 'Ang tamang pangungusap ay may wastong ayos ng mga salita: naglalaro sa labas habang umuulan.', icon: '✍️' },
      { q: 'Piliin ang wastong ispeling ng salitang "sagot sa isang sulat".', options: ['sagutan', 'sagsagot', 'sagutin', 'sagutanin'], answer: 2, topic: "Verbal", explanation: 'Ang tamang salita ay "sagutin" (to reply).', icon: '🔤' },
      { q: 'Piliin ang tamang salita: "The committee ___ approved the proposal."', options: ['have', 'has', 'are', 'were'], answer: 1, topic: "Verbal", explanation: 'Ang "committee" ay kolektibong pangngalan at itinuturing isahan, kaya "has."', icon: '📋' },
      { q: 'Piliin ang sentence na may TAMANG grammar.', options: ['Me and him went to the mall.', 'He and I went to the mall.', 'Him and me went to the mall.', 'I and him went to the mall.'], answer: 1, topic: "Verbal", explanation: 'Sa subject position, gumamit ng subjective pronouns: "He and I."', icon: '✍️' },
      // ===== Clerical Ability =====
      { q: 'Clerical: Piliin ang kopyang magkakapareho: `KR3D 88LM 2200`', options: ['KR3D 88LM 2200', 'KR3D 88LM 2201', 'KR3D 88Lm 2200', 'KR3D 88LM 2250'], answer: 0, topic: "Clerical", explanation: 'Eksaktong kopya: KR3D 88LM 2200.', icon: '🔍' },
      { q: 'Clerical: Ayusin sa alphabetical order: Juan, Maria, Ana, Ben', options: ['Ana, Ben, Juan, Maria', 'Juan, Maria, Ana, Ben', 'Ben, Ana, Juan, Maria', 'Maria, Juan, Ben, Ana'], answer: 0, topic: "Clerical", explanation: 'Sa alphabetical: Ana, Ben, Juan, Maria.', icon: '🔤' },
      { q: 'Clerical: Ilang beses lumitaw ang letrang "i" sa "Sinisigaw"?', options: ['2', '3', '4', '5'], answer: 1, topic: "Clerical", explanation: 'S-i-n-i-s-i-g-a-w: tatlong letrang "i".', icon: '🔡' },
      { q: 'Clerical: Alin ang tamang ispeling?', options: ['Febuary', 'Februray', 'February', 'Feburuary'], answer: 2, topic: "Clerical", explanation: 'Ang tamang spelling ay "February."', icon: '🗓️' },
      { q: 'Clerical: Piliin ang kopyang magkakapareho: `A7 C4.2 D9-01`', options: ['A7 C4.2 D9-01', 'A7 C4.2 D9-O1', 'A7 C4.3 D9-01', 'A7 C4.2 D8-01'], answer: 0, topic: "Clerical", explanation: 'Eksaktong kopya: A7 C4.2 D9-01.', icon: '🔍' },
      // ===== Numerical Ability =====
      { q: 'Kung ang 12 lapis ay ₱96, magkano ang 5 lapis?', options: ['₱35', '₱40', '₱45', '₱50'], answer: 1, topic: "Numerical", explanation: '96 ÷ 12 = 8 bawat lapis; 5 × 8 = ₱40.', icon: '✏️' },
      { q: 'I-solve: 20% ng 250', options: ['40', '50', '60', '80'], answer: 1, topic: "Numerical", explanation: '250 × 0.20 = 50.', icon: '➗' },
      { q: 'Ano ang susunod na numero: 5, 9, 13, 17, ____?', options: ['19', '21', '22', '25'], answer: 1, topic: "Numerical", explanation: 'Dagdagan ng +4 bawat numero: 17 + 4 = 21.', icon: '🔢' },
      { q: 'Kung ang ratio ng guro : mag-aaral ay 1 : 25, at may 75 mag-aaral, ilan ang guro?', options: ['2', '3', '4', '5'], answer: 1, topic: "Numerical", explanation: '75 ÷ 25 = 3 guro.', icon: '🍎' },
      { q: 'Kung ang isang sako ng bigas ay ₱1,800 at may 75% na diskwento, magkano ang babayaran?', options: ['₱350', '₱750', '₱450', '₱1,350'], answer: 2, topic: "Numerical", explanation: '1800 × 0.25 = ₱450 (25% na lang ang babayaran).', icon: '🌾' },
      ...extraTest3,
      ...lawNonPro,
    ],
  },
  {
    id: 4,
    title: 'Practice Test #4 — Civil Service Professional',
    blurb: 'General Information, Verbal, Numerical & Analytical — mas mataas na antas ng pag-iisip.',
    premium: true,
    examType: 'professional',
    sampleCount: 10,
    bank: [
      // ===== General Information =====
      { q: 'Sino ang nagtataglay ng kapangyarihang magsagawa ng batas (legislative power) sa Pilipinas?', options: ['Pangulo', 'Kongreso', 'Korte Suprema', 'Sandatahang Lakas'], answer: 1, topic: "General Info", explanation: 'Ang kapangyarihang lehislatibo ay nasa Kongreso (Senado at Kapulungan ng mga Kinatawan) ayon sa Artikulo VI ng Saligang Batas.', icon: '🏛️' },
      { q: 'Alin ang pangunahing tungkulin ng Hudisyal na sangay?', options: ['Gumawa ng batas', 'Sipat ang mga kaso at ipatupad ang batas', 'Magpatupad ng mga programang pangkabuhayan', 'Pamahalaan ang mga lokal na pamahalaan'], answer: 1, topic: "General Info", explanation: 'Ang hudisyal na sangay, pinamumunuan ng Korte Suprema, ay pumapatnubay sa bansa na maging null ng mga labis-tama mga kaso, at magpapatupad ng batas.', icon: '⚖️' },
      { q: 'Sa ilalim ng R.A. 6713, ano ang pangalawang "tenet" ng paghahandog ng serbisyong publiko?', options: ['Politikal na Neutralidad', 'Propesyonalismo', 'Katarungan at Katapatan', 'Awtokrasya'], answer: 1, topic: "General Info", explanation: 'Ang RA 6713 ay nagtataguyod ng commitment to public interest, professionalism, justness and sincerity, political neutrality, at responsiveness sa publiko.', icon: '👔' },
      { q: 'Ano ang pangunahing gamit ng Commission on Human Rights (CHR)?', options: ['Mangolekta ng buwis', 'Protektahan at itaguyod ang karapatang pantao', 'Magtayo ng kalsada', 'Mamahala ng barangay'], answer: 1, topic: "General Info", explanation: 'Ang CHR ay isang independiyenteng konstitusyonal na katawan na nagproprotekta at nagtataguyod ng mga karapatang pantao sa Pilipinas.', icon: '🤝' },
      { q: 'Aling batas ang tinatawag na "Ecological Solid Waste Management Act"?', options: ['RA 6713', 'RA 9003', 'RA 8749', 'RA 9275'], answer: 1, topic: "General Info", explanation: 'Ang R.A. 9003 o Ecological Solid Waste Management Act of 2000.', icon: '♻️' },
      { q: 'Ang pagmamahal sa bansa at pagsuporta sa konstitusyon ay itinuturing na ___.', options: ['Opsyonal', 'Tungkulin ng bawat mamamayan', 'Para lamang sa gobyerno', 'Hindi kailangan'], answer: 1, topic: "General Info", explanation: 'Ayon sa Artikulo II ng Saligang Batas, ang pagkamaka-bayan at pagsuporta sa konstitusyon ay tungkulin ng bawat mamamayan.', icon: '🇵🇭' },
      // ===== Verbal Ability =====
      { q: 'Piliin ang tamang salita: "Each of the candidates ___ a unique platform."', options: ['have', 'has', 'are', 'were'], answer: 1, topic: "Verbal", explanation: '"Each" ay isahan, kaya "has."', icon: '🗳️' },
      { q: 'Piliin ang mali sa pangungusap: "He likes very much to the music."', options: ['very much', 'likes', 'to', 'music'], answer: 2, topic: "Verbal", explanation: 'Ang tamang phrase ay "likes the music" — walang "to."', icon: '⚠️' },
      { q: 'Piliin ang salitang KASINGKAHULUGAN ng "maingat".', options: ['Pabaya', 'Masipag', 'Maîngaî', 'Mahinahon'], answer: 3, topic: "Verbal", explanation: 'Ang "maingat" na kahulugan ay maunawain at mahinahong gumagawa — ang pinakamalapit ay "mahinahon."', icon: '🇵🇭' },
      { q: 'Sentence completion: "The new policy ___ widely supported by the community."', options: ['is', 'are', 'were', 'be'], answer: 0, topic: "Verbal", explanation: '"Policy" ay isahan, kaya "is."', icon: '✍️' },
      { q: 'Error recognition: Alin ang mali sa pangungusap: "She don.t like to attend the meeting."', options: ['She', "don't", 'to attend', 'the meeting'], answer: 1, topic: "Verbal", explanation: 'Ang tamang negative para sa "she" ay "doesn.t" — kaya ang "don.t" ang mali.', icon: '⚠️' },
      // ===== Numerical Ability =====
      { q: 'Kung ang x + 5 = 12, ano ang x?', options: ['5', '7', '12', '17'], answer: 1, topic: "Numerical", explanation: 'x = 12 − 5 = 7.', icon: '🧮' },
      { q: 'Kung 3 manggagawa ang makapag-ayos ng bahay sa 6 na araw, ilang araw ang kailangan ng 6 na tao?', options: ['1', '2', '3', '6'], answer: 2, topic: "Numerical", explanation: 'Dobleng manggagawa = kalahating oras: 6 ÷ 2 = 3 araw.', icon: '🏗️' },
      { q: 'Sa isang set ng datos: 4, 5, 6, 6, 7, 8, ano ang median?', options: ['5', '6', '6.5', '7'], answer: 1, topic: "Numerical", explanation: 'Ang median ay ang gitnang halaga ng maayos na datos: 6.', icon: '📈' },
      { q: 'Ano ang susunod: 3, 6, 12, 24, ____?', options: ['30', '36', '48', '60'], answer: 2, topic: "Numerical", explanation: 'Bawat numero ay dumoble: 24 × 2 = 48.', icon: '🔢' },
      // ===== Analytical Ability =====
      { q: 'Analogical reasoning: KUNG KAGUBATAN : PUNO, ang AKLATAN : _____', options: ['Bahay', 'Librarian', 'Aklat', 'Paaralan'], answer: 2, topic: "Analytical", explanation: 'Ang kagubatan ay puno ng puno; ang aklatan ay puno ng aklat.', icon: '🌳' },
      { q: 'Kung ang lahat ng Estudyante ay masipag, at si Pedro ay Estudyante, ano ang tiyak?', options: ['Si Pedro ay masipag.', 'Si Pedro ay hindi masipag.', 'Si Pedro ay hindi Estudyante.', 'Hindi lahat ng masipag ay Estudyante.'], answer: 0, topic: "Analytical", explanation: 'Deduktibong lohika: kung lahat ng A ay B at si Pedro ay A, si Pedro ay B.', icon: '🧠' },
      { q: 'Logical sequence: Punan ang blangko: 1, 4, 9, 16, 25, ____', options: ['27', '30', '36', '49'], answer: 2, topic: "Analytical", explanation: 'Mga perfect square: 1², 2², 3², 4², 5² → 6² = 36.', icon: '🧮' },
      { q: 'Symbolic logic: Kung ang "★" ay nangangahulugang "mas malaki kaysa", alin ang totoo?', options: ['7 ★ 3', '3 ★ 7', '5 ★ 5', '2 ★ 9'], answer: 0, topic: "Analytical", explanation: '"Mas malaki kaysa" — ang 7 ay mas malaki sa 3, kaya 7 ★ 3 ang totoo.', icon: '🔣' },
      { q: 'Identifying assumptions: Sa pahayag na "Kailangan ng budget para sa edukasyon" — ano ang ipinapalagay?', options: ['Lahat ay may pera', 'Mahalaga ang edukasyon', 'Walang gobyerno', 'Bawal ang bumoto'], answer: 1, topic: "Analytical", explanation: 'Ang pahayag ay ipinapalagay na mahalaga ang edukasyon upang bigyang-dahilan ang budget.', icon: '🎓' },
      { q: 'Data interpretation: Sa 200 respondents, 40% ang pumili ng "Bata". Ilan ang pumili ng "Pang-adulto"?', options: ['40', '100', '120', '140'], answer: 2, topic: "Analytical", explanation: 'Kung 40% ay Bata, ang 60% ay Pang-adulto: 200 × 0.60 = 120.', icon: '📊' },
      { q: 'Ano ang HINDI totoo tungkol sa rebolusyon?', options: ['Isang malaking pagbabago.', 'Maaaring mapayapa.', 'Laging marahas.', 'Nababago ang lipunan.'], answer: 2, topic: "Analytical", explanation: 'Ang rebolusyon ay hindi palaging marahas — maaaring mapayapa ang pagbabago.', icon: '🌐' },
      ...extraTest4,
      ...lawPro,
    ],
  },
];